"""
pdf_loader.py — Phase 1: Load a PDF from raw bytes into LangChain Documents.

WHY: We accept raw bytes (not a file path) so the user's upload never needs
to be saved to disk. Each page becomes its own Document so that page number
metadata survives all the way to retrieval time.
"""

import io
import uuid
from typing import List

import pypdf
from langchain_core.documents import Document


def load_pdf(pdf_bytes: bytes, doc_id: str) -> List[Document]:
    """
    Parse raw PDF bytes and return one LangChain Document per page.

    Args:
        pdf_bytes: Raw bytes of the PDF file (e.g. from an upload).
        doc_id:    Unique identifier for this document (generated by build_index).

    Returns:
        A list of Documents, one per page, with metadata:
            doc_id     – identifies the source PDF
            page_num   – 1-based page number
            chunk_type – always "text" here; tables are added later
            parent_id  – empty string (set during chunking)
            token_count– approximate (character count / 4)

    Raises:
        ValueError: if pdf_bytes is not a valid PDF or the PDF has no pages.
    """

    if not pdf_bytes:
        raise ValueError("pdf_bytes is empty — nothing to load.")

    # Parse the PDF entirely in memory; no temp file is created
    try:
        reader = pypdf.PdfReader(io.BytesIO(pdf_bytes))
    except Exception as exc:
        raise ValueError(f"Could not parse PDF: {exc}") from exc

    if len(reader.pages) == 0:
        raise ValueError("PDF has zero pages.")

    documents: List[Document] = []

    for page_index, page in enumerate(reader.pages):
        page_num = page_index + 1  # 1-based page numbers are easier to explain

        # extract_text() returns "" if the page has no extractable text
        text = page.extract_text() or ""
        text = text.strip()

        if not text:
            # We keep a placeholder so the page still appears in metadata;
            # an empty page is not an error — scanned PDFs often have these.
            text = f"[Page {page_num}: no extractable text]"

        # Rough token estimate: 1 token ≈ 4 characters (common heuristic)
        approx_tokens = len(text) // 4

        doc = Document(
            page_content=text,
            metadata={
                "doc_id": doc_id,
                "page_num": page_num,
                "chunk_type": "text",
                "parent_id": "",          # filled in during chunking
                "token_count": approx_tokens,
            },
        )
        documents.append(doc)

    return documents
